version: '3.8'

x-logging: &default-logging
  driver: json-file
  options:
    max-size: 100M

services:
  judge0-server:
    image: judge0/judge0:1.13.0
    container_name: judge0-server
    volumes:
      - ./tmp:/tmp
    ports:
      - "2358:2358"
    privileged: true
    environment:
      # Redis Configuration
      - REDIS_HOST=judge0-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      
      # Database Configuration
      - POSTGRES_HOST=judge0-db
      - POSTGRES_DB=${POSTGRES_DB:-judge0}
      - POSTGRES_USER=${POSTGRES_USER:-judge0}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-YourSecurePassword123}
      
      # Judge0 Configuration
      - RAILS_ENV=production
      - RAILS_MAX_THREADS=5
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-your_secret_key_base_here}
      
      # Security & Performance
      - MAX_QUEUE_SIZE=100
      - MAX_CPU_TIME_LIMIT=15
      - MAX_WALL_TIME_LIMIT=20
      - MAX_MEMORY_LIMIT=128000
      - MAX_STACK_LIMIT=64000
      - MAX_PROCESSES_AND_OR_THREADS=30
      - MAX_NUMBER_OF_RUNS=20
      - MAX_REDIRECT_FOLLOWS=3
      - MAX_EXTRACT_SIZE=10240
      - MAINTENANCE_MODE=false
      - ENABLE_WAIT_RESULT=true
      - ENABLE_COMPILER_OPTIONS=false
      - ALLOWED_LANGUAGES_FOR_COMPILE_OPTIONS=""
      - ENABLE_COMMAND_LINE_ARGUMENTS=false
      - ENABLE_SUBMISSION_DELETE=false
      - ENABLE_CALLBACKS=true
      - CALLBACKS_MAX_TRIES=3
      - CALLBACKS_TIMEOUT=5
      
      # File Upload & Security
      - ENABLE_ADDITIONAL_FILES=false
      - MAX_ADDITIONAL_FILES_SIZE_LIMIT=5242880
      - MAX_TOTAL_SIZE_LIMIT=52428800
      - USE_DOCS_AS_HOMEPAGE=false
      - ALLOW_ORIGIN=*
      - ALLOW_HEADERS=*
      
      # Worker Configuration
      - COUNT_OF_WORKERS=2
      - INTERVAL=0.1
      
      # Submission Configuration
      - MAX_SUBMISSION_BATCH_SIZE=20
      - SUBMISSION_CACHE_DURATION=86400
      
      # API Configuration
      - ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=false
      - ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=false
      - MAX_CPU_EXTRA_TIME=1
      - MAX_WALL_EXTRA_TIME=5
      - ISOLATE_PATH=/usr/local/bin/isolate
    logging: *default-logging
    restart: unless-stopped
    depends_on:
      - judge0-db
      - judge0-redis
    networks:
      - judge0-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:2358/system_info || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  judge0-workers:
    image: judge0/judge0:1.13.0
    container_name: judge0-workers
    command: ["rails", "resque:work", "QUEUE=*"]
    volumes:
      - ./tmp:/tmp
    privileged: true
    environment:
      # Same environment variables as server
      - REDIS_HOST=judge0-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - POSTGRES_HOST=judge0-db
      - POSTGRES_DB=${POSTGRES_DB:-judge0}
      - POSTGRES_USER=${POSTGRES_USER:-judge0}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-YourSecurePassword123}
      - RAILS_ENV=production
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-your_secret_key_base_here}
      - COUNT_OF_WORKERS=2
      - INTERVAL=0.1
      - MAX_CPU_TIME_LIMIT=15
      - MAX_WALL_TIME_LIMIT=20
      - MAX_MEMORY_LIMIT=128000
      - MAX_STACK_LIMIT=64000
      - MAX_PROCESSES_AND_OR_THREADS=30
      - ISOLATE_PATH=/usr/local/bin/isolate
    logging: *default-logging
    restart: unless-stopped
    depends_on:
      - judge0-db
      - judge0-redis
    networks:
      - judge0-network
    scale: 2

  judge0-db:
    image: postgres:13
    container_name: judge0-db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-YourSecurePassword123}
      - POSTGRES_USER=${POSTGRES_USER:-judge0}
      - POSTGRES_DB=${POSTGRES_DB:-judge0}
    volumes:
      - judge0-db-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    logging: *default-logging
    restart: unless-stopped
    networks:
      - judge0-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-judge0} -d ${POSTGRES_DB:-judge0}"]
      interval: 10s
      timeout: 5s
      retries: 5

  judge0-redis:
    image: redis:6.2-alpine
    container_name: judge0-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-}
    volumes:
      - judge0-redis-data:/data
    logging: *default-logging
    restart: unless-stopped
    networks:
      - judge0-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  judge0-network:
    driver: bridge

volumes:
  judge0-db-data:
    driver: local
  judge0-redis-data:
    driver: local 